version: '2'

services:

    communiteer-perf-results:
        restart: always
        image: nginx:1.15.9
        container_name: comm-perf-results
        volumes:
            - ./results:/usr/share/nginx/html
        ports:
            - "8081:80"
